//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.08.04 at 12:31:39 PM CEST 
//


package net.hrkac.jaxb.unmarshal.model;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for MuseumType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="MuseumType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="City" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="MuseumName" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="PermanentExhibition" type="{}ExhibitionType" minOccurs="0"/>
 *         &lt;element name="SpecialExhibition" type="{}ExhibitionType" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="childrenAllowed" type="{http://www.w3.org/2001/XMLSchema}boolean" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "MuseumType", propOrder = {
    "city",
    "museumName",
    "permanentExhibition",
    "specialExhibition"
})
public class MuseumType {

    @XmlElement(name = "City")
    protected String city;
    @XmlElement(name = "MuseumName")
    protected String museumName;
    @XmlElement(name = "PermanentExhibition")
    protected ExhibitionType permanentExhibition;
    @XmlElement(name = "SpecialExhibition")
    protected ExhibitionType specialExhibition;
    @XmlAttribute(name = "childrenAllowed")
    protected Boolean childrenAllowed;

    /**
     * Gets the value of the city property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCity() {
        return city;
    }

    /**
     * Sets the value of the city property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCity(String value) {
        this.city = value;
    }

    /**
     * Gets the value of the museumName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMuseumName() {
        return museumName;
    }

    /**
     * Sets the value of the museumName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMuseumName(String value) {
        this.museumName = value;
    }

    /**
     * Gets the value of the permanentExhibition property.
     * 
     * @return
     *     possible object is
     *     {@link ExhibitionType }
     *     
     */
    public ExhibitionType getPermanentExhibition() {
        return permanentExhibition;
    }

    /**
     * Sets the value of the permanentExhibition property.
     * 
     * @param value
     *     allowed object is
     *     {@link ExhibitionType }
     *     
     */
    public void setPermanentExhibition(ExhibitionType value) {
        this.permanentExhibition = value;
    }

    /**
     * Gets the value of the specialExhibition property.
     * 
     * @return
     *     possible object is
     *     {@link ExhibitionType }
     *     
     */
    public ExhibitionType getSpecialExhibition() {
        return specialExhibition;
    }

    /**
     * Sets the value of the specialExhibition property.
     * 
     * @param value
     *     allowed object is
     *     {@link ExhibitionType }
     *     
     */
    public void setSpecialExhibition(ExhibitionType value) {
        this.specialExhibition = value;
    }

    /**
     * Gets the value of the childrenAllowed property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isChildrenAllowed() {
        return childrenAllowed;
    }

    /**
     * Sets the value of the childrenAllowed property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setChildrenAllowed(Boolean value) {
        this.childrenAllowed = value;
    }

}
