//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.08.03 at 10:04:09 PM CEST 
//


package net.hrkac.jaxb.unmarshal.model;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the net.hrkac.jaxb.unmarshal.model package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _MUSEUM_QNAME = new QName("", "MUSEUM");
    private final static QName _EXHIBITION_QNAME = new QName("", "EXHIBITION");
    private final static QName _MUSEUMS_QNAME = new QName("", "MUSEUMS");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: net.hrkac.jaxb.unmarshal.model
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Museums }
     * 
     */
    public Museums createMuseums() {
        return new Museums();
    }

    /**
     * Create an instance of {@link Exhibition }
     * 
     */
    public Exhibition createExhibition() {
        return new Exhibition();
    }

    /**
     * Create an instance of {@link Museum }
     * 
     */
    public Museum createMuseum() {
        return new Museum();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Museum }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "MUSEUM")
    public JAXBElement<Museum> createMUSEUM(Museum value) {
        return new JAXBElement<Museum>(_MUSEUM_QNAME, Museum.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Exhibition }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "EXHIBITION")
    public JAXBElement<Exhibition> createEXHIBITION(Exhibition value) {
        return new JAXBElement<Exhibition>(_EXHIBITION_QNAME, Exhibition.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Museums }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "MUSEUMS")
    public JAXBElement<Museums> createMUSEUMS(Museums value) {
        return new JAXBElement<Museums>(_MUSEUMS_QNAME, Museums.class, null, value);
    }

}
