//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.08.04 at 12:31:39 PM CEST 
//


package net.hrkac.jaxb.unmarshal.model;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the net.hrkac.jaxb.unmarshal.model package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _Museum_QNAME = new QName("", "Museum");
    private final static QName _Museums_QNAME = new QName("", "Museums");
    private final static QName _Exhibition_QNAME = new QName("", "Exhibition");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: net.hrkac.jaxb.unmarshal.model
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link MuseumType }
     * 
     */
    public MuseumType createMuseumType() {
        return new MuseumType();
    }

    /**
     * Create an instance of {@link MuseumsType }
     * 
     */
    public MuseumsType createMuseumsType() {
        return new MuseumsType();
    }

    /**
     * Create an instance of {@link ExhibitionType }
     * 
     */
    public ExhibitionType createExhibitionType() {
        return new ExhibitionType();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link MuseumType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "Museum")
    public JAXBElement<MuseumType> createMuseum(MuseumType value) {
        return new JAXBElement<MuseumType>(_Museum_QNAME, MuseumType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link MuseumsType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "Museums")
    public JAXBElement<MuseumsType> createMuseums(MuseumsType value) {
        return new JAXBElement<MuseumsType>(_Museums_QNAME, MuseumsType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ExhibitionType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "Exhibition")
    public JAXBElement<ExhibitionType> createExhibition(ExhibitionType value) {
        return new JAXBElement<ExhibitionType>(_Exhibition_QNAME, ExhibitionType.class, null, value);
    }

}
